language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot_practice *
  - mkdir -p deploy
  - mv springboot_practice.zip deploy/springboot_practice.zip

deploy:
  - provider: s3
      access_key_id: AKIA6N37R6RXGZLPHWIW
      secret_access_key: ••••••••••••••••
      bucket: freelec-springboot-build-strange # s3 버킷
      region: ap-northeast-2
      skip_cleanup: true
      acl: private # zip 파일 접근은 private로
      local_dir: deploy # before_deploy에서 생성한 디렉토리
      wait_until_deployed: true


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - strange.hoon7@gmail.com